#!/bin/sh

PREREQ=""
DESCRIPTION="Setting things up to enable restricted drivers..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

cat > /root/etc/init.d/enable-drivers <<EOF
#!/bin/bash
for d in \$(jockey-gtk -l | cut -d ' ' -f 1) ; do
    jockey-gtk -e "\$d"
done
EOF
ln -s /etc/init.d/enable-drivers /root/etc/rcS.d/S80enable-drivers

log_end_msg
