#!/bin/sh

PREREQ=""
DESCRIPTION="Putting help message on the greeter screen..."


prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac
. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

chroot /root gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults --type bool --set /apps/gdm/simple-greeter/banner_message_enable "true"
chroot /root gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults --type string --set /apps/gdm/simple-greeter/banner_message_text 'You can log in as "ubuntu" or (if you have internet) your Athena user. Log in as "ubuntu" to install or to configure internet.'

log_end_msg
