#!/bin/sh

PREREQ=""
DESCRIPTION="Adding live-cd-version athinfo query..."

VERSION=unknown

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

echo "live-cd-version echo $VERSION" >> /etc/athena/athinfo.defs

log_end_msg
